services:
  frontend:
    build:
      context: ./frontend
      target: ${BUILD_ENV}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - PORT=${FRONTEND_PORT}
      - REACT_APP_QUESTION_SVC_PORT=${QUESTION_SVC_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - user-service
      - question-service

  user-service:
    build:
      context: ./backend/UserService
      target: ${BUILD_ENV}
    ports:
      - ${USER_SVC_PORT}:${USER_SVC_PORT}
    environment:
      - PORT=${USER_SVC_PORT}
      - DB_LOCAL_URI=${USER_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/UserService:/app
      - /app/node_modules

  question-service:
    build:
      context: ./backend/QuestionService
      target: ${BUILD_ENV}
    ports:
      - ${QUESTION_SVC_PORT}:${QUESTION_SVC_PORT}
    environment:
      - PORT=${QUESTION_SVC_PORT}
      - MONGOURI=${QUESTION_DB_URI}
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./backend/QuestionService:/app
      - /app/node_modules

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./scripts/kafka-create-topics.sh:/kafka-create-topics.sh
    command: sh -c "
      chmod +x /kafka-create-topics.sh &&
      /etc/confluent/docker/run &
      echo 'Waiting for Kafka to start...' &&
      cub kafka-ready -b localhost:9092 1 30 &&
      echo 'Kafka is ready. Creating topics...' &&
      /kafka-create-topics.sh &&
      echo 'Topics created. Kafka is fully ready.' &&
      wait"